### ISSUE TITLE
Order status only one of three options

### ISSUE THREAD

**Issue by dazza041** [thephpleague/omnipay-sagepay#104]
As per the notes for both v2 and v3, SagePay only ever seems to return one of three states: STATUS_COMPLETED, STATUS_PENDING or, and the default, STATUS_FAILED.

We have an integration problem, where we are using the authorize() function and this always sends a DEFERRED payment. In some cases payments should/could be AUTHENTICATE. However, using the authorize() callback we're only ever going to get DEFERRED. A setTxType() would be ideal in side DirectGateway. Which, if using Authorize, you could override the default action.

Similarly, when payments are returned acceptNotification() will only ever return one of three states: STATUS_COMPLETED, STATUS_PENDING or, and the default, STATUS_FAILED. This was already raised here: https://github.com/thephpleague/omnipay-sagepay/pull/42

Therefore, each successful transaction that returns an AUTHENTICATED state technically fails, even though its not failed. My understanding of "$gateway->capture([...]);" is that it will release the funds immediately and stops using the acceptNotification(), which has been advised in issue #69.

**Comment by judgej** [comment]
The Notify handler can receive any of these statuses:

* OK - a PAYMENT being authorised
* NOTAUTHED - TBC
* PENDING - TBC
* ABORT - transaction cancelled (manually or automatically) before it is settled
* REJECTED - a PAYMENT, DEFERRED or AUTHENTICATE failing CC validation or verification.
* AUTHENTICATED - card details grabbed in AUTHENTICATE transaction with 3D Secure
* REGISTERED - card details grabbed in AUTHENTICATE transaction without 3D Secure
* ERROR - TBC

An ABORT can happen:

* By a user canceling while entering CC details.
* By a VOID being sent before settlement the morning after a PAYMENT, AUTHORISE or RELEASE.
* A DEFERRED transaction unused for 30 days.
* Am AUTHORISED payment unused for 90 days (30 days for MC).

**Comment by judgej** [comment]
Release 3.1.0
