### ISSUE TITLE
Transactionid is empty in sagepay notification post?

### ISSUE THREAD

**Issue by RocketTechDev** [thephpleague/omnipay-sagepay#110]
In the notification sagepay sends to my server, the transactionid is null?

```
 public function handle()
      {
      	// Set the final url sagepay should redirect to
      	$finalUrl = URL::getSiteUrl() . 'order/complete';
      	Log::info('Final URl set to '.$finalUrl);
      	
      	    // Get the gateway driver.
           $gateway = OmniPay::create('SagePay_Server')
                  ->setVendor('my_vendor_key')
                  ->setTestMode(true);

            $notification = $gateway->acceptNotification();
            
            Log::info('transactionId looks like this ==>: '. $notification->getTransactionId());

            /**
             * Retrieve the transaction from the database.
             * Security key is local from first response
             */
            $transaction = Storage::getYAML('shop/trans/' . $notification->getTransactionId());
            $securityKey = $transaction['transactionReference'];

            Log::info('Security key looks like this ==>: '. $securityKey);

            /**
             * Now the signature can be checked
             */
            $notification->setSecurityKey($securityKey);                 
            $response = $notification->send();

            if (! $response->isValid()) {
		    // Respond to Sage Pay indicating we are not accepting anything about this message.
		    // You might want to log `$request->getData()` first, for later analysis.

		    $response->invalid($finalUrl, 'Signature not valid - goodbye');
		}

		Storage::putYAML('shop/orders/' . $transactionId, [
                  'status'         => $response->getTransactionStatus(),
                  'listing_status' => '<span class="order-status ' . $response->getTransactionStatus() . '">' . Shop::t('status.' . $response->getTransactionStatus()) . '</span>',
                  'message'        => $response->getMessage(),
                  'notifyData'     => $response->getData(),
            ]);

            $response->confirm($finalUrl);

      }
```
 
I'm sure this isn't sagepays error, but it would be handy to know why I cant see the notification post?

**Comment by judgej** [comment]
Is this the 3.x (latest) branch you are using, or are you still on 2.x?

**Comment by RocketTechDev** [comment]
Thanks for the quick response!

I'm using version 3.x

**Comment by judgej** [comment]
Could you do me a favour and try `dev-master` to see if it works any differently? It shouldn't - I'm not aware that this wasn't working previously.

I noticed you are doing this:

```php
$securityKey = $transaction['transactionReference'];
$notification->setSecurityKey($securityKey);
```

I'm not sure that will work. If this is how it is documented, I'll fix that.

Instead,:

```php
$transactionReference = $transaction['transactionReference'];
$notification->setTransactionReference($transactionReference);
```

The `transactionReference` is a JSON string that *contains* the `securityKey`. All the notification handler needs is the `securityKey`. If you give it the `transactionReference` *as a transactionReference*, then it will extract the `securityKey` from it. If you have stored the `securityKey` separately, then supply it *as a securityKey* in the way you have done so.

The `securityKey` will be a short string like this example: *3J9EB5JE8B*.

**Comment by RocketTechDev** [comment]
I've updated the two lines you suggested, and updated the package to use `dev-master`. The error has now changed. I stay on sagepay's server with this as the result:

```
Server error 5006: Unable to redirect to Vendor's web site. The Vendor failed to provide a RedirectionURL.
```

and in my log I see a new error:

```
[2018-09-20 16:01:18] production.INFO: Final URl set to http://34.247.32.24/order/complete  
[2018-09-20 16:01:18] production.INFO: transactionId looks like this ==>:   
[2018-09-20 16:01:18] production.INFO: transaction data ==> Array
(
)
  
[2018-09-20 16:01:18] production.INFO: Security key looks like this ==>:   
[2018-09-20 16:01:18] production.ERROR: Omnipay\Common\Exception\InvalidResponseException: Cannot confirm an invalid notification in /vendor/omnipay/sagepay/src/Message/ServerNotifyRequest.php:121
Stack trace:
#0 /var/www/html/dev/core/Http/Controllers/SagepayController.php(64): Omnipay\SagePay\Message\ServerNotifyRequest->confirm('http://34.247.3...')
```

**Comment by judgej** [comment]
Your data is empty, that's the strange thing. How does `$_POST` look? It's like the driver is not seeing anything posted. Maybe try [Postman](https://www.getpostman.com/) to POST to your endpoint and see what it can see? Send in some of the parameters I've listed above. The trouble with the notification callback is that you are working blind when working with the gateway, but you can emulate the gateway to get some more clues.

**Comment by judgej** [comment]
I've tried both of these on the test account:

    $notifyServerRequest->setSecurityKey($secret);
    $notifyServerRequest->setTransactionReference($transactionReference);

Both work for me. I do get the `$notifyServerRequest->setTransactionId()` for looking up the saved security key and transaction references, which each look like this:

> securityKey: YTOREOUYQF
> transactionReference: {"SecurityKey":"YTOREOUYQF","VPSTxId":"{46858FAC-3FB7-F835-7A32-C40EB4EA8BAB}","VendorTxCode":"phpne-demo-20265472"}

Did you have any luck trying *Postman*?

I've pushed a few more changes to master. They are a small number of fixes and many refactoring changes (mainly pulling things together to make extensions for newer features easier and more flexible).

**Comment by RocketTechDev** [comment]
Hello,

I've tried a few tests but received an invalid response, I suspect I'm not sending a correctly formed message.

> Status=INVALID
> RedirectUrl=http:/xxx/order/complete
> StatusDetail=Signature not valid - goodbye

My postman post message looks like this:

```
/payment-gateway-process?SecurityKey=WTACNNMQBQ&VPSTxId=B1794633-C8A1-E210-36AB-8CAB3B1D98FF&VendorTxCode=2018-09-20_10-54-43.1037
```

**Comment by judgej** [comment]
I believe it is a `POST` rather than a `GET`, so the parameters need to be entered as POST parameters rather than GET parameters in the URL.

However, that response you are getting looks okay for what was sent. Maybe just try posting your `VendorTxCode` and see if your notification handler can see it in `$notifyRequest->getTransactionId()`. This seems to be the point where it's failing - data is sent in a POST but the Omnipay driver can't see it. Everything subsequently fails as a consequence.

Maybe also log `$_POST` in your handler when running against Sage Pay.

**Comment by RocketTechDev** [comment]
Quite right! With postman set up correctly for a `post` message, I can see the following in my log:

```
2018-09-21 10:59:56] production.INFO: transactionId looks like this ==>: 2018-09-20_10-54-43.1037  
[2018-09-21 10:59:56] production.INFO: transaction data ==> Array
(
    [SecurityKey] => WTACNNMQBQ
    [VPSTxId] => B1794633-C8A1-E210-36AB-8CAB3B1D98FF
    [VendorTxCode] => 2018-09-20_10-54-43.1037
)
```

However the response I get back is:

```
Status=INVALID
RedirectUrl=http://xxx/order/complete
StatusDetail=Signature not valid - goodbye
```

**Comment by judgej** [comment]
That's good, so your code is certainly seeing the POST data. The signature will be wrong because *everything* needs to be right in the message for it to pass. You can bypass the signature check, but make sure you have other checks in place to be certain the response has come from Sage Pay and nobody else constructing a fake "success" notification.

Switching back to the gateway, does this still not work against live Sage Pay?

**Comment by RocketTechDev** [comment]
Well, it's now gone through on the test server. And I can see the full post message in the log. If I ever discover what happened I'll post back here for everyone's reference. Thanks for your help.

**Comment by judgej** [comment]
Well, that's good news. And sratchy-head news. I assume this is for `dev-master` still. Maybe there are some fixes in there that I'm not aware of, just from the reorganisation. Perhaps I need to get that released sooner than later (with a bit more test coverage on the notify handler).

**Comment by judgej** [comment]
Closing for now. Reopen if you find the source and believe it to be a bug.
