### ISSUE TITLE
Possible missing step in Readme

### ISSUE THREAD

**Issue by pmhou** [thephpleague/omnipay-sagepay#115]
I'm working on a Server integration and have been following the steps in the readme doc but hit a snag when it came to implementing the notification handler.

```php
// Returns instance of \Omnipay\SagePay\Message\ServerNotifyRequest
$request = $gateway->acceptNotification();
```

Following the readme, it states that the request variable is used to respond with invalid, error or confirm
```php
if (! $request->isValid()) {
    // Respond to Sage Pay indicating we are not accepting anything about this message.
    // You might want to log `$request->getData()` first, for later analysis.

    $request->invalid($nextUrl, 'Signature not valid - goodbye');
}
```

However those methods exist within `\Omnipay\SagePay\Message\ServerNotifyResponse`. It appears you need to do the following, which is missed out of the readme.

```php
// Returns instance of \Omnipay\SagePay\Message\ServerNotifyResponse
$response = $request->sendData($request->getData());

// Now you can do $response->invalid|error|confirm()
```

Could you confirm whether this is correct? Thanks.

**Comment by judgej** [comment]
If you are using the older Omnipay 2.x then what you describe will still be the case, and the [documentation for that branch](https://github.com/thephpleague/omnipay-sagepay/tree/2.x) reflects that.

For the newer 3.0+ branch the `send()` step is optional, as there is only a `ServerNotifyRequest` class present, and that does everything that previously the `ServerNotifyRequest` and `ServerNotifyResponse` did between them.

Which version are you using?

**Comment by pmhou** [comment]
Thanks for the quick response. My composer.lock is referencing 3.0.1

**Comment by judgej** [comment]
Actually, it's 3.1.0 the notify handler changed - not 3.0.x - sorry for misleading. 3.1.0 was released last night, so you may be comparing the newer documentation with a slightly older release. Try 3.1.0 :-)

**Comment by pmhou** [comment]
Yep, that's done it! Thanks for confirming 👍

**Comment by judgej** [comment]
np - let me know if you find any other issues, as this is a new release with lots of changes, but is stable. Your name is familiar - PHPNE, FrontendNE?

**Comment by pmhou** [comment]
Will do. And yes, PHPNE - small world!
