### ISSUE TITLE
Docs: ExitOnResponse default is actually false

### ISSUE THREAD

**Issue by jamieburchell** [thephpleague/omnipay-sagepay#128]
> The confirm(), error() and reject() methods will all exit the application immediately to prevent additional output being added to the response. You can disable this by setting the exitOnResponse option

It seems that the default is now `false`

**Comment by judgej** [comment]
Do we just need to change the documentation? It makes more sense this way to me - no library should be exiting on behalf of whatever framework it is in.

**Comment by judgej** [comment]
Updated docs.
