### ISSUE TITLE
SagePay Strong Customer Authentication and 3D Secure v2

### ISSUE THREAD

**Issue by UdyW** [thephpleague/omnipay-sagepay#136]
Sage pay now has a requirement to do all ecommerce transactions to be processed via secured industry protocol such as 3D Secure. They will not allow transactions which does not have Strong Customer Authentication. [More details](https://www.sagepay.co.uk/support/12/36/3d-secure-explained).
Is this issues being addressed already? or will there be any updated regarding this?

**Comment by judgej** [comment]
Please close this issue if you think this previous issue covers the changes: https://github.com/thephpleague/omnipay-sagepay/issues/135

**Comment by UdyW** [comment]
It is. Many thanks.

**Comment by judgej** [comment]
Ta. We are at the stage of going through the docs to see what needs to be done. So eyes are on it, but no progress with implementation *so far as I am aware*.
