### ISSUE TITLE
Abort Defer transaction requires txAuthNo

### ISSUE THREAD

**Issue by pendledt** [thephpleague/omnipay-sagepay#149]
As I currently understand it, the following SagePay Direct transactions can be aborted:

* Deferred before it's released
* Authorisation before it's captured

To process the abort, Deferred requires the `TxAuthNo` whereas Authorisation does not.

At the moment, the `SharedAbortRequest` class doesn't include `TxAuthNo` so aborting a deferred transaction results in an error with message "3072 : The TxAuthNo field is missing."

Please correct me if I have this wrong, otherwise I will submit a PR for the change.

Thanks

**Comment by pendledt** [comment]
For some reason `SharedAbortRequest` was different to the current version. Updated and everything is working.

**Comment by judgej** [comment]
Thank you for letting me know.
