### ISSUE TITLE
Deprecated: preg_match() Passing null in getClientIp()

### ISSUE THREAD

**Issue by jamieburchell** [thephpleague/omnipay-sagepay#177]
I'm seeing this on PHP 8.1 using v4:

`Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated`

Coming from [here](https://github.com/thephpleague/omnipay-sagepay/blob/v4.0.0/src/Message/DirectAuthorizeRequest.php#L138) (`omnipay/sagepay/src/Message/DirectAuthorizeRequest.php in Omnipay\SagePay\Message\DirectAuthorizeRequest::getClientIp at line 138`)

I'm not sure why the IP can be `null` at that point, but here we are.

**Comment by judgej** [comment]
Thank you. It looks like `parent::getClientIp()` is returning null, which is understandable if running tests and the tests don't explicitly set the IP address.

It needs to skip the regex check if the IP address is already null, or is not a string.

**Comment by jamieburchell** [comment]
Strange thing is, this wasn't the result of running tests. This happened in production.

**Comment by judgej** [comment]
Just [checked the core](https://github.com/thephpleague/omnipay-common/blob/e1ebc22615f14219d31cefdf62d7036feb228b1c/src/Common/Message/AbstractRequest.php#L557) and I completely forgot that it is the application that supplies the IP address. I'm guessing your application isn't providing the client IP. A quick workaround would be to pass in anything that is not a valid IPv4 and not a null. An empty string would work. 

    $request->setClientIp('');

Just for some background, what the regex does, is just make sure the IP address is IPv4, and blanks it out if it isn't. Sage Pay would error if the IP wasn't in the `a.b.c.d` format. So it is not essential the IP address is sent (though for 3DS v2 maybe it is, but not at this point?)

**Comment by judgej** [comment]
Yeah, PR looks good. It was PHP 8.1 that has brought this deprecation notice - what you are [not] setting is good too. I was just trying to think of a quick workaround that would fix the problem for you.

**Comment by jamieburchell** [comment]
Great. My confusion was that the other place I'm running this code is in fact PHP 7.4. So yeah, in PHP 8.1 this notice is a thing if not setting the IP.

**Comment by jamieburchell** [comment]
I don't think I can assist with refactoring that. I believe a lot of the Server code extends the Direct code?

**Comment by judgej** [comment]
Thanks again - I've merged and made a patch release.
