### ISSUE TITLE
"NotificationURL format is invalid" when using a local route

### ISSUE THREAD

**Issue by markmead** [thephpleague/omnipay-sagepay#188]
Hello there 👋

I'm trying to update to v3 making use of `SagePay_Server` but when I use a named/local route for `notifyUrl` I hit the following error:

```
3011 : The NotificationURL format is invalid.
```

Here's the code that is causing the issue:

```php
'notifyUrl' => route('payment.sagepay.notify'),
```

Results to something like `http://localhost:12345/payment/notify`.

Strangely (to me), if I pass in a route like `http:://www.something123.test/` it works fine.

It's worth noting that I am using Lando.

**Comment by judgej** [comment]
Though having read again, that's not the problem you are having! 

The 3011 comes from the remote server. Could it be only accepting https?

**Comment by judgej** [comment]
Error documentation here https://www.opayo.co.uk/search/all?keyword=3011

**Comment by markmead** [comment]
I think HTTP is fine, but this line is the answer.

> The NotificationURL field must contain a Fully Qualified Domain Name

Thankfully, Lando provides a `http://name.land.site/` URL, I'll give that a whirl.

**Comment by judgej** [comment]
Oh course, that makes sense. You can use a service such as https://ngrok.com/ to tunnel the notifications to your local machine, if you aren't working on a public domain.

**Comment by markmead** [comment]
NGROK was the ticket, thanks a lot!

Now it's working I'm a little lost on how you handle where to redirect a user when they click "Cancel", I've looked through the README but I can't seem to find anything that answers this.

**Comment by markmead** [comment]
Ignore me, it was an issue in the code, hah! Thanks for all the help!
