### ISSUE TITLE
New Elavon URLs

### ISSUE THREAD

**Issue by matt5mith** [thephpleague/omnipay-sagepay#194]
With Opayo now rebranding to Elevon, will the package be updated to use the new URLs?  The reported deadline is 31st March 2024.

**Comment by judgej** [comment]
Totally. I won't have time to look at this myself for a couple of weeks, but it's on my list. Hopefully it will be a simple change to the URLs at https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Message/AbstractRequest.php#L61 though I haven't read if there are other changes yet.

If you've tried the URLs, and *they just work* ™️ then a PR would be most welcome.

**Comment by judgej** [comment]
Actually just noticed PR #193 with these changes. Hero :-)

**Comment by matt5mith** [comment]
Awesome, thanks @judgej.  I'm happy to help if you need anything.

**Comment by judgej** [comment]
Pre-repease 4.1.1 is now available to try. It should [still] work across PHP 7.4 to 8.1, and Symfony 3 to 6.

**Comment by judgej** [comment]
I'm hopefully going to be trying this out in a production application running older PHP 7.4 within the week. If that works, I'll move the `4.1.1` tag from pre-release to release, assuming no reports of problems using `4.1.1` with later PHP versions?

**Comment by matt5mith** [comment]
Thanks @judgej.  We've done some initial testing with Opayo/Elavon testMode set to true and everything appears to be working fine.  That was also on PHP v7.4.

**Comment by judgej** [comment]
This is running fine for us now in production under PHP 7.4. With that, other reports, and the tests, I'm going to mark release 4.1.1 as live and close this issue. Any problems are best reported in a new issue, but reference back here if it helps to identify what broke it.

**Comment by dathwa** [comment]
Hello. We use Sagepay server. With the new updates on the live site, we are now getting these errors on the sagepay server after submitting payment...
It's was previously working fine. Any ideas anyone?
Thanks

"Server error 5006: Unable to redirect to Vendor's web site. The Vendor failed to provide a RedirectionURL."
"HTTP error 500: The request was unsuccessful due to an unexpected condition encountered by the server."

**Comment by dathwa** [comment]
> Hello. We use Sagepay server. With the new updates on the live site, we are now getting these errors on the sagepay server after submitting payment... It's was previously working fine. Any ideas anyone? Thanks
> 
> "Server error 5006: Unable to redirect to Vendor's web site. The Vendor failed to provide a RedirectionURL." "HTTP error 500: The request was unsuccessful due to an unexpected condition encountered by the server."

Please ignore. I downgraded package to `"omnipay/sagepay": "4.0.1"` and the problem persists. No idea what has changed on the servers.

**Comment by judgej** [comment]
@dathwa it might be worth raising this on a new issue. I've not seen it reported elsewhere yet, but it may still be a problem with some edge cases.

**Comment by judgej** [comment]
Just for the record, here are the latest URLs:

## Pi Integration

https://developer.elavon.com/products/opayo/v1/api-reference (under "Getting your API credentials" section):

TEST: https://test.sagepay.com/mysagepay
LIVE: https://live.sagepay.com/mysagepay

## Direct Integration

https://developer.elavon.com/products/opayo-direct/v1/testing#test-urls

TEST:

REGISTRATION: https://sandbox.opayo.eu.elavon.com/gateway/service/vspdirect-register.vsp
3D-SECURE CALLBACK: https://sandbox.opayo.eu.elavon.com/gateway/service/direct3dcallback.vsp
PAYPAL COMPLETION: https://sandbox.opayo.eu.elavon.com/gateway/service/complete.vsp

LIVE:

REGISTRATION: https://live.opayo.eu.elavon.com/gateway/service/vspdirect-register.vsp
3D-SECURE CALLBACK: https://live.opayo.eu.elavon.com/gateway/service/direct3dcallback.vsp
PAYPAL COMPLETION: https://live.opayo.eu.elavon.com/gateway/service/complete.vsp

## Server Integration

https://developer.elavon.com/products/opayo-server/v1/test-and-live-urls-4515

TEST: https://sandbox.opayo.eu.elavon.com/gateway/service/vspserver-register.vsp
LIVE: https://live.opayo.eu.elavon.com/gateway/service/vspserver-register.vsp

## Form Integration

https://developer.elavon.com/products/opayo-forms/v1/test-and-live-urls-4633

TEST: https://sandbox.opayo.eu.elavon.com/gateway/service/vspform-register.vsp
LIVE: https://live.opayo.eu.elavon.com/gateway/service/vspform-register.vsp

## Shared (Server and Direct, possibly Form)

https://developer.elavon.com/products/opayo-shared-api/v1/urls-4714

TEST:

ABORT: https://sandbox.opayo.eu.elavon.com/gateway/service/abort.vsp
RELEASE: https://sandbox.opayo.eu.elavon.com/gateway/service/release.vsp
REFUND: https://sandbox.opayo.eu.elavon.com/gateway/service/refund.vsp
REPEAT and REPEATDEFERRED: https://sandbox.opayo.eu.elavon.com/gateway/service/repeat.vsp
VOID: https://sandbox.opayo.eu.elavon.com/gateway/service/void.vsp
AUTHORISE: https://sandbox.opayo.eu.elavon.com/gateway/service/authorise.vsp
CANCEL: https://sandbox.opayo.eu.elavon.com/gateway/service/cancel.vsp
REMOVETOKEN: https://sandbox.opayo.eu.elavon.com/gateway/service/removetoken.vsp

LIVE:

ABORT: https://live.opayo.eu.elavon.com/gateway/service/abort.vsp
RELEASE: https://live.opayo.eu.elavon.com/gateway/service/release.vsp
REFUND: https://live.opayo.eu.elavon.com/gateway/service/refund.vsp
REPEAT and REPEATDEFERRED: https://live.opayo.eu.elavon.com/gateway/service/repeat.vsp
VOID: https://live.opayo.eu.elavon.com/gateway/service/void.vsp
AUTHORISE: https://live.opayo.eu.elavon.com/gateway/service/authorise.vsp
CANCEL: https://live.opayo.eu.elavon.com/gateway/service/cancel.vsp
REMOVETOKEN: https://live.opayo.eu.elavon.com/gateway/service/removetoken.vsp
