### ISSUE TITLE
Some fields might not be present when assembling the signature

### ISSUE THREAD

**Issue by jamieburchell** [thephpleague/omnipay-sagepay#33]
I think there could be a potential issue with the signature function which expects the following fields to always be present (see comments as to why they might not be)

```
TxAuthNo // Only present if Status is OK.
CAVV // Only present if the 3DSecureStatus field is OK or ATTEMPTONLY
AddressStatus // Paypal only
PayerStatus // Paypal only
```

In addition, the spec states that the vendor name must be lowercased prior to hashing.

Edit:

Futhermore, if the transaction status is ABORT - these fields aren't present either:

```
AVSCV2
AddressResult
PostCodeResult
CV2Result
3DSecureStatus
CardType
Last4Digits
TxAuthNo
```

**Comment by judgej** [comment]
These fields should all return an empty string "" if they are not present, so the hash ought still to work. In the V3.00 Server spec it says:

> If a field is returned without a value this should not be included in the string [to be hashed].

So the empty strings can be concatenated together without any effect on the hash. It will be worth and end-to-end test though, and perhaps writing some tests, just to make sure all those values *are* empty strings and not nulls.

Also in the spec:

> Please ensure the VendorName is lower case prior to hashing.

Good point. That can be fixed. I suspect all vendor names already are going to be lower-case, but best to be explicit (that warning is in the spec for a reason).

**Comment by jamieburchell** [comment]
I suspected that the function would probably return an empty string hence why the hashing function continues to work, but I question it because the last four items that are expected to be optional have a second parameter of an empty string - I'm assuming as a default if the item is not present. As you say, it might be returning something falsey other than an empty string.

**Comment by jamieburchell** [comment]
Hmm, I actually think maybe `$this->httpRequest->request->get()` will return null if the parameter is missing, but I'm having a hard time finding the function signature.

Not sure why that would still work, unless PHP is converting it to an empty string.

**Comment by judgej** [comment]
Possibly:

~~~php
php > echo "hello" . null . "world";
helloworld
php > echo strlen("hello" . null . "world");
10
php > echo "hello" . false . "world";
helloworld
php > echo strlen("hello" . false . "world");
10
~~~

Seems like it should work, by a lucky fluke ;-)

Just to show a different type conversion:

~~~php
php > echo "hello" . true . "world";
hello1world
~~~

**Comment by judgej** [comment]
Here is the spec for `get()`:

http://api.symfony.com/2.0/Symfony/Component/HttpFoundation/Request.html#method_get

It will return a NULL by default, if the (POST) http value is not set. They should all be set to default to and empty string IMO, just to be a little more explicit on what is going on in that signature function.

**Comment by jamieburchell** [comment]
I agree. Especially when IMO the SagePay spec doesn't do a good job of describing accurately which fields will be present when!

**Comment by judgej** [comment]
PR #54 puts in empty string defaults for unsent fields.
