### ISSUE TITLE
Response getStatus() should be getCode()

### ISSUE THREAD

**Issue by judgej** [thephpleague/omnipay-sagepay#36]
The common abstract response message defines a `getCode()` method that returns the raw status code from the gateway. SagePay does not use this, and instead uses `getStatus()`. This means the raw response cannot be captured in a consistent way to other gateways, resulting in an exception required in the code.

The fix should be to add `getCode` to the response messages, where-ever `getStatus()` is used. Maybe deprecate `getStatus()` to be removed in V3.0

I can do this - just not for a couple of weeks, so adding this as a note here.

**Comment by judgej** [comment]
I'll mark it as a bug, since `getCode()` behaves differently to other gateways (always returns null).

**Comment by nearkingdom** [comment]
Hi @judgej - we are trying to integrate Sage Pay using Omnipay into our system using Craft Commerce and [potentially pinpointed the same issue](https://github.com/thephpleague/omnipay-sagepay/issues/63).

**Comment by judgej** [comment]
Damn, this one has slipped away from me for a year and three days :-(

I'll try and get it in today, as I'm doing some gateway stuff this week.

**Comment by judgej** [comment]
I suspect also `getMessage()` needs to return `$data['StatusDetail'`.
