### ISSUE TITLE
Deferred payments on Server Gateway

### ISSUE THREAD

**Issue by Rattler3** [thephpleague/omnipay-sagepay#41]
You cannot currently do DEFERRED payments using the Server gateway as the action is not mutable, [as you can see here](https://github.com/thephpleague/omnipay-sagepay/blob/cf655b3ba1d9e7f66991768af06e3da898a28812/src/Message/ServerPurchaseRequest.php#L10).

Do you have any plans for implementing this?

**Comment by Rattler3** [comment]
I have submitted a pull request that will fix this issue. #42

**Comment by judgej** [comment]
Sorry this has been hanging around for so long. The PR was closed, as the `DEFERRED` transactions are (and always have been) already implemented as the OmniPay `Authorize` functionality.
