### ISSUE TITLE
Support Sage integration via Basket

### ISSUE THREAD

**Issue by coatesap** [thephpleague/omnipay-sagepay#55]
It turns out that, frustratingly, although we added Basket XML support in #50 / #51, this method is not supported by any of the Sage accounting packages (Line 50, etc). This means that although we can now send full details of the purchased items to SagePay, they won't ever be picked up in Sage.

This was one of the main benefits of adding this functionality, as it's quite common for merchants to use SagePay on the basis that it will cut down their manual data entry in Sage. 

After a long call with their support team, the reality seems to be that it's only the old basket field that is supported by the Sage packages. As an additional gotcha (although I haven't tested this) SagePay will throw an error if you try to send both versions of the basket. They have said that they may at some point in the future support the new BasketXML parameter in the Sage packages, but it didn't sound imminent.

This leaves us in a difficult situation, where if we want to support both versions, we will probably have to let the developer set a flag to say which version of the basket they wish to send. 

There has been some work done by @benjam-es in #8 on the older parameter, so it may be worth us resurrecting this, and combining it with a flag to choose which version to send. 

Happy to help out with this once anyone who's interested has had chance to air their thoughts...

**Comment by judgej** [comment]
This is very unfortunate, and par the course for Sage. I've ranted before about their internal politics (looking at the bigger picture seems to be discouraged) and attitude towards the technology they put in front of their users, so I won't bore you with that here.

The XML basket has been in place for three, four years now? They have had plenty of time to incorporate that into their other products. Until someone kicks down the internal competition barriers in that organisation, this simply is not going to happen.

So yeah, I guess it needs to be an option on the basket, so generating the basket and putting the result into the correct field can be selected.

The non-XML basket has its own limitations to be aware of - special characters (those separating the fields) must be removed, the total must be added up and supplied as the final line (not looking forward to currency arithmetic), and the whole thing has a length limit (something like 512 or 1024 characters, but isn't documented). It also must be provided in an ISO8859-1 characterset.

So I would renamed [getItemData()](https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Message/AbstractRequest.php#L192) to something like `getItemDataXml()`, as we know that works, then write `getItemData()` to get the basket contents according to the basket type flag.

I have some code for generating the old style basket somewhere, which I'll dig out.

**Comment by judgej** [comment]
Actually, you don't need to provide the order total in the basket, but the line totals MUST add up to the order total. With the XML basket, at least in the test system, that rule is not enforced by Sage Pay.

**Comment by judgej** [comment]
> Both the Basket field and the BasketXML field are optional. If basket information is to be supplied, you cannot pass both the Basket and the BasketXML field, only one of them needs to be passed.

**Comment by judgej** [comment]
According to this:

http://www.sagepay.co.uk/support/12/36/protocol-3-00-basket-xml

the old text basket did NOT need to add up to the total transaction amount, but the newer XML basket DOES. I have found the complete opposite TBH, so I'm not sure what is happening there. It could just be that test and live gateways have slightly different behaviour.

**Comment by coatesap** [comment]
Yep, it's a real pain that we have to spend time on this. Do you have a copy of the code you've got for the old-style basket I could have a look at and compare with the code in PR #8?

**Comment by judgej** [comment]
Here's a method from an older project, warts and all. It may give you some ideas, but I'm sure it can be improved immensely:

~~~php
    // Create a structured and formatted basket string from the line data.
    // Each item contains the array: 'item', 'quantity', 'value', 'tax', 'total', 'line_total'.
    // Or a numeric-indexed array in the same order.
    // Each value refers to a per-item value, except for line_total.
    // Values may be numeric or string, and will be formatted if numeric.
    // A NULL value will be replaced with the SagePay spacer string.
    // TODO: how to deal with the wrong characterset?

    public static function create_basket($items = array())
    {
        $basket = '';
        $sep = ':';
        $sep_repl = ';';
        $spc = '---';
        $count = 0;
        $value_list = array('value', 'tax', 'total', 'line_total');

        if (count($items) == 0) return $basket;

        // Set the total number of items first.
        // Actually, do this at the end, once we know how many items are valid.
        //$basket .= count($items);

        foreach($items as $item) {
            // Pull out the line of data.
            if (isset($item[0])) {
                list($item, $quantity, $value, $tax, $total, $line_total) = $item;
            } else {
                extract($item);
            }

            // TODO: make sure we have valid data for the line.

            // Knock the item description into shape.
            // Any HTML is allowed, but we do need to remove any separator characters.
            $item = str_replace($sep, $sep_repl, $item);

            if (!isset($quantity)) {
                $quantity = $spc;
            } elseif (!is_numeric($quantity)) {
                continue;
            } else {
                $quantity = trim($quantity);
            }

            // Format all the value fields using the same rules.
            foreach($value_list as $value_field) {
                if (!isset($$value_field)) {
                    $$value_field = $spc;
                } elseif(is_numeric($$value_field)) {
                    // We are assuming the localle is correctly set here.
                    // TODO: use the currency set for the SagePay transaction to ensure
                    // the formatting is correct.
                    $$value_field = money_format('%!.2n', $$value_field);
                } elseif (is_string($$value_field)) {
                    $$value_field = trim($$value_field);
                } else {
                    continue;
                }
            }

            // Add the line to the basket string.
            $count += 1;
            $basket .= $sep . $item . $sep . $quantity;
            foreach($value_list as $value_field) $basket .= $sep . $$value_field;
        }

        // Add the item count to the start.
        if ($count > 0) $basket = $count . $basket;

        return $basket;
    }
~~~

**Comment by judgej** [comment]
I asked Sage Pay about bringing the basket types more into line. The answer was that each are handled by different teams, and they don't work all that closely yet. I suspect it is one of those things where the teams (Sage Pay vs Sage Accounting) are in a stalemate about who exactly is going to pay for this integration, but I'm just speculating there. So anyway, no plans to fix this from Sage, but they recognise it's a pain.

**Comment by judgej** [comment]
So quick poll: do we need to support both types of baskets - the old-style CSV basket and the XML basket?

**Comment by coatesap** [comment]
We've added optional support for the old-style CSV basket in our fork of this repo, and have now been running it in production for a few weeks now with some users on the CSV, and some on the XML. It's all gone fine as far as I know, but once we've had chance to confirm, I'll get a pull request opened to merge back into this repo.

As far as the wider community goes, I do think it makes sense to support both, as some users will need the Sage integration provided by the CSV format, whilst others may need any new features provided by the XML format (which off the top of my head, I can't remember). Also it makes sense to keep the XML version in for future proofing, as presumably one day in the future Sagepay will drop the CSV format.

**Comment by judgej** [comment]
If the two types of basket support completely different, and non-overlapping features in the back-end, then yes, it makes a lot of sense to support both in this gateway driver.

Could you provide a quick summary of how a developer would choose which basket type to use with your latest fork? Is it an option to set, and which is the default?

**Comment by coatesap** [comment]
Hi Jason, I've just updated the readme on our fork to provide a bit of background for other devs: https://github.com/coatesap/omnipay-sagepay#basket-format

**Comment by judgej** [comment]
Brilliant, that's great. I was interviewed by Sage Pay yesterday so they could get some feedback on the beta programme for their REST API (with the JS front-end like Stripe and the new Authorize.Net API). I brought this specific issue up as a problem developers have - needing the integration capabilities of both types of basket, and the problem it causes for library developers having to develop for both types of basket. They agreed it needed improving. No idea which teams that feedback will eventually get to, but hopefully it will have a net benefit to the REST API when they get to incorporate the basket (which is not there are all yet).

**Comment by judgej** [comment]
Thanks Del. I've just been overloaded with other stuff the last month or so, and had little time to look at this. *Hopefully* things will settle down soon... :pray:
