### ISSUE TITLE
Token billing: createCard(), updateCard(), deleteCard()

### ISSUE THREAD

**Issue by judgej** [thephpleague/omnipay-sagepay#75]
See core OmniPay documentation:

https://github.com/thephpleague/omnipay#token-billing

This driver uses:
- `registerToken()` for `createCard()`
- `completeRegistration()` to complete `registerToken` (should probably be `completeCreateCard()`)
- `TokenRemoval` request for `deleteCard()`
- `createToken` when generating a card token during authorize instead of (perhaps) `createCard`
- `token` to pass in a saved token during authorize instead of `cardReference`

These now need knocking into shape for consistency with other gateways (at least for consistency with the core documentation).

**Comment by judgej** [comment]
OmniPay Common has both get/setToken and get/setCardReference. I'm going to assume they can be used interchangeably, so will just stick to "token" here for now.

**Comment by delatbabel** [comment]
Hi Jason, that's not strictly correct.  cardReference is the correct parameter. token is used for things like oAuth access tokens that are part of the authentication process. See PayPal REST  for an example. Some gateway plugins do use them interchangeably but that's not the correct usage for token.

**Comment by judgej** [comment]
Thanks for the clarification. I'll fix that.

**Comment by judgej** [comment]
Okay, I'm going for:

* `$gateway->createCardReference()` to create a standalone card reference (gets card details from the user and generates a card reference for it, stored at Sage Pay.
* `$gateway->deleteCardReference()` to tell Sage Pay to forget a stored card reference.
* `completeRegistration()` for handling the return from a Server `createCardReference()` has been merged into `acceptNotification()` (i.e. one notification handler to handle all Server callbacks).
* The parameter on payments to tell Sage Pay to create a card reference with a payment is now `set/getCreateCardReference()`
* The parameter on payments to tell Sage Pay to store (for future use) a card reference with a payment is now `set/getStoreCardReference()`

**Comment by lukeholder** [comment]
@delatbabel where can we discuss gateway implementations settling on the correct usage of token vs cardReference? Do you know if this will be cleaned up in Omnipay 3?

**Comment by judgej** [comment]
I suspect you may need to [start a new issue here](https://github.com/thephpleague/omnipay-common/issues).

**Comment by judgej** [comment]
Just to note, these changes leave all the old "token" based method names active, but just mark them as deprecated. The intention is to remove them in OmniPay 3.0.

**Comment by judgej** [comment]
In release [2.4.0](https://github.com/thephpleague/omnipay-sagepay/releases/tag/2.4.0)
