### ISSUE TITLE
Different CardHolder and billing name

### ISSUE THREAD

**Issue by jamslater** [thephpleague/omnipay-sagepay#81]
The [Direct integration documentation](http://www.sagepay.co.uk/file/12236/download-document/DIRECT_Integration_and_Protocol_Guidelines_010814.pdf) (page 43) makes a distinction between `CardHolder` ("This should be the name displayed on the card.") and `BillingFirstnames`/`BillingSurname` ("Customer billing details").

Currently there's no way of setting these to different values, because `CardHolder` is [set](https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Message/DirectAuthorizeRequest.php#L106) by:

`$data['CardHolder'] = $this->getCard()->getName();` which in turn calls `$this->getBillingName()`

This is especially problematic if the card holder name is a single word (e.g. name of a company). That fails Sagepay's validation of billing forename(s) and surname making it impossible to create the transaction, even if we have a valid name and surname to provide.

I'm not sure how best to tackle this. Perhaps in Omnipay, where card name and billing name are conflated? Or in this driver by making a distinction between the CreditCard and the billing information attached to the transaction.

Locally I've subclassed CreditCard and overridden `getName`.

**Comment by judgej** [comment]
My hunch is to fix it in this driver, for now. However, see what other drivers have done, and follow their lead where possible, and then this can make its way to OmniPay Common (the core).

**Comment by delatbabel** [comment]
It's not unusual for a gateway to have a distinction between card holder and customer, however they aren't usually referred to as CardHolderName and BillingName because I would assume that BillingName is the person that's actually being billed (hence the card holder).  However it's also not unusual for a gateway to be weird and different to all other gateways.

**Comment by judgej** [comment]
Even when the card is named after the person being billed, the card can have a very specific name printed on it that should ideally be used. The first name and last name fields are usually linked to billing details in the gateway - who is responsible for making sure a payment is made, but not necessarily who is paying.

For the few gateways I know, these are the card holder fields in use, which are separate from the billing first name and last name:

* PAYONE: `cardholder`
* Sage Pay Direct: `CardHolder`
* Sage Pay Pi (REST): `cardholderName`
* Helcim.JS + Direct: `cardholderName`

**Comment by jamslater** [comment]
The omnipay-barclays-epdq driver [appears to](https://github.com/samvaughton/omnipay-barclays-epdq/blob/master/src/Omnipay/BarclaysEpdq/Message/EssentialPurchaseRequest.php) support three different types of name _and_ address:

- card name / address
- invoicing name / address
- delivery name / address

**Comment by judgej** [comment]
@delatbabel `Billing Name` actually is quite commonly used to represent the billed party in many gateways. Separate billing and shipping details is useful metadata to capture, and can also feed into invoicing and accounting functions where the gateway supplier also provides those. In addition, an address check can optionally be performed against the billing details - a failed address check may be flagged up, but it does not (normally) prevent payment from being taken, so the billing address does not need to match the cardholder address.

**Comment by judgej** [comment]
Hmm, so github has now taken to automatically closing issues that are referenced by a PR that is merged in. Not sure I like that.

**Comment by judgej** [comment]
In release [2.4.0](https://github.com/thephpleague/omnipay-sagepay/releases/tag/2.4.0)
