### ISSUE TITLE
New Release please?

### ISSUE THREAD

**Issue by joshbrw** [thephpleague/omnipay-sagepay#86]
Why has there not been a release for so long? The documentation states that I should use the `->accepNotification()` method but I can see that wasn't implemented until Q4 2016, whereas the last release was in Feb 2016.

For now I'm going to have to use `dev-master`, but obviously moving forward I don't want to have to do that.

**Comment by judgej** [comment]
Okay, I'll make it my priority next week (just busy as hell until this Sunday though).

Yes, do use dev-master in the meantime. There should be nothing unstable in it at the moment, and we'll aim to keep it that way.

**Comment by joshbrw** [comment]
Awesome - thanks @judgej!

**Comment by judgej** [comment]
I got too busy, and allowed too many changes to go through without a release. Then it kind makes it more difficult to release stuff without knowing I am available to react quickly enough to inevitable issues as people upgrade. Sorry about that - I really should be more on top of this.

**Comment by joshbrw** [comment]
Don't worry - we all get busy :)

**Comment by judgej** [comment]
Released as [2.4.0](https://github.com/thephpleague/omnipay-sagepay/releases/tag/2.4.0)

**Comment by joshbrw** [comment]
Thanks @judgej!
