### ISSUE TITLE
Latest 2.x version requires omnipay/common: ~2.4

### ISSUE THREAD

**Issue by judgej** [thephpleague/omnipay-sagepay#92]
The master version with the `acceptNotification` support requires `omnipay/common` of at least 2.4

It is on `~2.0` right now.

**Comment by biggins** [comment]
@judgej could we get the latest version of this tagged so composer will pick up the change?

**Comment by judgej** [comment]
I've tagged it as v2.5.0

It has a lot of refactoring, but I've added tests and it should still work as before.

**Comment by biggins** [comment]
Thanks @judgej much appreciated!

**Comment by judgej** [comment]
I'm still not sure what the tags have not been picked up by packagist, and I have not heard back from any enquiries I've made. I don't suppose you can see something I've not spotted, @biggins ?

**Comment by judgej** [comment]
It's a broken branch, apparently. I'll take a look in the morning.

https://github.com/composer/packagist/issues/840

**Comment by judgej** [comment]
I've renamed branch `30alpha1` to `30alpha1-dev` and that has allowed the packagist sync to complete. Instructions for renaming a branch here:

https://stackoverflow.com/a/9525744/218208

**Comment by judgej** [comment]
I should have closed this a while ago. It's in release 2.5.1
